//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class isgagroupe1Entities1 : DbContext
{
    public isgagroupe1Entities1()
        : base("name=isgagroupe1Entities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Etudiant> Etudiant { get; set; }
    public virtual DbSet<ExamenSet1> ExamenSet11 { get; set; }
    public virtual DbSet<ModuleSet> ModuleSet1 { get; set; }
}
