//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Etudiant
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Etudiant()
    {
        this.ExamenSet1 = new HashSet<ExamenSet1>();
    }

    public int id { get; set; }
    public string nom { get; set; }
    public string prenom { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string gender { get; set; }
    public string photo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ExamenSet1> ExamenSet1 { get; set; }
}

public partial class ExamenSet1
{
    public int Id { get; set; }
    public double note { get; set; }
    public System.DateTime date { get; set; }
    public int Etudiant_id { get; set; }
    public int Module_Id { get; set; }

    public virtual Etudiant Etudiant { get; set; }
    public virtual ModuleSet ModuleSet { get; set; }
}

public partial class ModuleSet
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ModuleSet()
    {
        this.ExamenSet1 = new HashSet<ExamenSet1>();
    }

    public int Id { get; set; }
    public string intitule { get; set; }
    public double coiff { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ExamenSet1> ExamenSet1 { get; set; }
}
